# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-10-06 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodChannel',
            new_name='GoodsChannel',
        ),
    ]
